### ISSUE TITLE
View EventData in the Message Column

### ISSUE THREAD

**Issue by JodyBevan** [kmaki565/EventLook#46]
### Discussed in https://github.com/kmaki565/EventLook/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **JodyBevan** June  6, 2023</sup>
The application I used to develop with has an interface to send to the macOS Console, and the Windows Event Log. We can send our custom message. This shows up in the XML in the EventData.

This is an example of the EventData
<?xml version="1.0" encoding="utf-16"?>
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="4D Application" />
    <EventID Qualifiers="49152">7</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-06-06T07:30:19.6857157Z" />
    <EventRecordID>35166</EventRecordID>
    <Correlation />
    <Execution ProcessID="34820" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Manuel_Privado</Computer>
    <Security />
  </System>
  <EventData>
    <Data>                                            Deleted Files Folder does not exist at: C:\Users\villa\Desktop\IP test for Jody with logs\Infopool\DeletedFiles\</Data>
  </EventData>
</Event>

The Message column shows for all of these:
(EventLook) The description for the event cannot be found.

How do I get the Message column to show the text message in EventData?

I am currently using EventLook 1.1.1.0 (5/22/2023) that I downloaded from the Microsoft Store. I am using Windows 10.</div>

**Comment by kmaki565** [comment]
I think I understand the issue - `FormatDescription` failed to format message because metadata for the event was somewhat missing on your system ([reference](https://learn.microsoft.com/en-us/troubleshoot/windows/win32/evtformatmessage-formatted-string-event)).

In Windows Event Viewer, such event sometimes shows like this,
![image](https://github.com/kmaki565/EventLook/assets/16055659/1a07653d-1d83-47a4-a8c9-332ef6b8b8d4)

or sometimes shows as "The operation completed successfully." (as discussed in [stackoverflow](https://stackoverflow.com/questions/71128675/windows-10-event-viewer-id-description-problem)).

I made [a trial version](https://github.com/kmaki565/EventLook/tree/show-eventdata) to show EventData as in the Details view of Event Viewer when the issue occurs. Can you try the [artifact](https://github.com/kmaki565/EventLook/suites/13493270061/artifacts/741091317) on your machine?

I hesitate to adopt this as a default behavior, but I will consider adding this capability.

**Comment by JodyBevan** [comment]
kmaki565:

Sorry I took so long to get back to this. I was assigned lots of high priority code that I had to get done.

Today I set that work aside to try this artifact out.

This worked perfectly for me. I see exactly the messages from the 4D Application.

Thank you!

Will this enhancement make it into the Microsoft Store version? I would like the support team to have this version as well.

Thanks again

Jody Bevan

**Comment by kmaki565** [comment]
I'm glad it worked for you! I'll release the next version to Microsoft Store soon.

**Comment by kmaki565** [comment]
1.1.2 is now released in Microsoft Store. However, I am seeing a hang up issue (more often) with this version (https://github.com/kmaki565/EventLook/issues/50). Please try it out!

**Comment by JodyBevan** [comment]
kmaki565:

I will download it and try it out on my files.

Thanks

Jody

**Comment by JodyBevan** [comment]
kmaki565

I have downloaded version 1.1.2 from the MicroSoft store. I opened .evtx files from the application of interest that were sent to me. EventLook is showing our messages just fine. I see you added in (EventLook - dump of Event Data) at the start of the message. That does not bother me, and you likely want it there so that other users will know where this is coming from.

Thanks for your response. I will be updating my review!

Jody Bevan
