### ISSUE TITLE
Program became completely unresponsive (but under just what conditions I do not know)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kmaki565/EventLook#63]
I opened the program. I looked through some of its menus. I looked at the 'about' window. I discovered a little later that the program had become completely unresponsive - even the taskbar menu's 'quit' did not work. I have been unable to reproduce the problem (and, I am afraid, I have removed the program).

**Comment by kmaki565** [comment]
Yes, I knew there is a UX problem where the 'About' modal dialog window is easily lost. Once the window is covered by some other window, you need to find the window by the Alt+Tab shortcut key because you can't find it from the taskbar (as `ShowInTaskbar` of the window is set false).
I think I found [a solution](https://stackoverflow.com/a/6889353/5461938) for this issue and will add the fix to the next release. 
Thank you for reminding!
